name: moose
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Let's Pray
  - python=3.10
  - pip=24.*
  - pytorch=2.6.*
  - pytorch-cuda=12.4
  - torchvision=0.21.* # matches torch 2.6
  - torchaudio=2.6.*

  - numpy=1.26.* # GenMol pin; TR2D2 is flexible
  - pandas=2.2.* # newer than GenMolâ€™s 2.1.0,
  - scikit-learn
  - scipy=1.13.*
  - xgboost=3.0.5
  - rdkit # conda-forge build for TR2D2
  - pyyaml
  - tqdm
  - jupyterlab
  - matplotlib-base
  - seaborn

  # Hydra / Lightning family (align both repos)
  - pip:
      - lightning==2.5.5          #GenMol has 2.5.1
      - pytorch-lightning==2.5.5
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - omegaconf==2.3.0

      # Transformers / ESM / vision
      - transformers==4.56.2
      - fair-esm==2.0.0
      - timm==1.0.20
      - SmilesPE==0.0.3

      # Project-specifics
      - datasets==2.18.0
      - wandb==0.22.0
      - safe-mol
      - PyTDC==0.4.1
      - easydict
      - openbabel-wheel
      #- pathos==0.3.4
      - pathos==0.3.2
      - loguru==0.7.3
      - bionemo-moco==0.0.2.1
